[30/Apr/2014 08:39:37] ERROR [django.request:226] Internal Server Error: /articles/saveSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 121, in saveSlides
    name = metadata['articleMetaData']["name"]
NameError: global name 'metadata' is not defined
[30/Apr/2014 08:40:15] ERROR [django.request:226] Internal Server Error: /articles/saveSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 121, in saveSlides
    name = metaData['articleMetaData']["name"]
TypeError: string indices must be integers
[30/Apr/2014 08:40:46] ERROR [django.request:226] Internal Server Error: /articles/saveSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 122, in saveSlides
    name = metaData['articleMetaData']["name"]
TypeError: string indices must be integers
[30/Apr/2014 08:42:42] ERROR [django.request:226] Internal Server Error: /articles/saveSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 121, in saveSlides
    obj = json.loads(metaData)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 326, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 360, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
TypeError: expected string or buffer
[30/Apr/2014 08:43:07] ERROR [django.request:226] Internal Server Error: /articles/saveSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 123, in saveSlides
    obj1 = obj['articleMetaData']
KeyError: 'articleMetaData'
[30/Apr/2014 08:44:17] ERROR [django.request:226] Internal Server Error: /articles/saveSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 125, in saveSlides
    name = obj1["name"]
TypeError: string indices must be integers
[30/Apr/2014 08:44:50] DEBUG [articles.views:127] metaData is <type 'dict'>     ---------- ---------   {u'articleMetaData': u'{"TYPE":"METADATA","name":"object litreal explained","tags":"javascript ","zist":"secret sausages of javascript","initialSeed":5,"showNextButton":false,"uid":2}'}
[30/Apr/2014 08:44:50] DEBUG [articles.views:127] metaData is <type 'dict'>     ---------- ---------   {u'articleMetaData': u'{"TYPE":"METADATA","name":"object litreal explained","tags":"javascript ","zist":"secret sausages of javascript","initialSeed":5,"showNextButton":false,"uid":2}'}
[30/Apr/2014 08:44:50] ERROR [django.request:226] Internal Server Error: /articles/saveSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 134, in saveSlides
    a.tags.add(tags)
  File "/Library/Python/2.7/site-packages/taggit/managers.py", line 235, in __get__
    "before you can access their tags." % model.__name__)
ValueError: Article objects need to have a primary key value before you can access their tags.
[30/Apr/2014 08:45:27] ERROR [django.request:226] Internal Server Error: /articles/saveSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 134, in saveSlides
    a.tags.add(tags)
  File "/Library/Python/2.7/site-packages/taggit/managers.py", line 235, in __get__
    "before you can access their tags." % model.__name__)
ValueError: Article objects need to have a primary key value before you can access their tags.
[30/Apr/2014 08:51:44] ERROR [django.request:226] Internal Server Error: /articles/edit/1
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 90, in get_response
    response = middleware_method(request)
  File "/Library/Python/2.7/site-packages/django/middleware/common.py", line 71, in process_request
    if (not urlresolvers.is_valid_path(request.path_info, urlconf) and
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 573, in is_valid_path
    resolve(path, urlconf)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 453, in resolve
    return get_resolver(urlconf).resolve(path)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 318, in resolve
    for pattern in self.url_patterns:
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 346, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/Library/Python/2.7/site-packages/django/core/urlresolvers.py", line 341, in urlconf_module
    self._urlconf_module = import_module(self.urlconf_name)
  File "/Library/Python/2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/ajay/Tanicode/Tanicode/Tanicode/urls.py", line 10, in <module>
    url(r'^articles/', include('articles.urls')),
  File "/Library/Python/2.7/site-packages/django/conf/urls/__init__.py", line 26, in include
    urlconf_module = import_module(urlconf_module)
  File "/Library/Python/2.7/site-packages/django/utils/importlib.py", line 40, in import_module
    __import__(name)
  File "/ajay/Tanicode/Tanicode/articles/urls.py", line 5, in <module>
    from articles import views
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 64
    template = loader.get_template('articles/create.html')
                                                         ^
IndentationError: unindent does not match any outer indentation level
[30/Apr/2014 08:52:08] WARNING [django.request:145] Not Found: /articles/edit/favicon.png
[30/Apr/2014 08:52:29] WARNING [django.request:145] Not Found: /articles/edit/updateSlides
[30/Apr/2014 08:54:06] WARNING [django.request:145] Not Found: /updateSlides
[30/Apr/2014 08:55:10] WARNING [django.request:145] Not Found: /updateSlides
[30/Apr/2014 08:55:57] WARNING [django.request:145] Not Found: /articles/edit/updateSlides
[30/Apr/2014 08:58:36] DEBUG [articles.views:159] 1
[30/Apr/2014 08:58:36] DEBUG [articles.views:159] 1
[30/Apr/2014 08:58:43] WARNING [django.request:145] Not Found: /articles/viewArticle/1
[30/Apr/2014 08:58:51] WARNING [django.request:145] Not Found: /articles/viewArticle/1/favicon.png
[30/Apr/2014 09:26:17] DEBUG [articles.views:159] 1
[30/Apr/2014 09:26:17] DEBUG [articles.views:159] 1
[30/Apr/2014 09:26:37] WARNING [django.request:145] Not Found: /articles/viewArticle/1/
[30/Apr/2014 09:33:17] DEBUG [articles.views:159] 1
[30/Apr/2014 09:33:17] DEBUG [articles.views:159] 1
[30/Apr/2014 09:33:17] ERROR [django.request:226] Internal Server Error: /articles/edit/updateSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 182, in updateSlides
    a.tags.add(tags.split())
AttributeError: 'list' object has no attribute 'split'
[30/Apr/2014 09:33:49] DEBUG [articles.views:159] 1
[30/Apr/2014 09:33:49] DEBUG [articles.views:159] 1
[30/Apr/2014 09:33:49] ERROR [django.request:226] Internal Server Error: /articles/edit/updateSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 182, in updateSlides
    a.tags.add(tags)
  File "/Library/Python/2.7/site-packages/taggit/utils.py", line 128, in inner
    return func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/taggit/managers.py", line 134, in add
    if not isinstance(t, self.through.tag_model())
TypeError: unhashable type: 'list'
[30/Apr/2014 09:34:33] DEBUG [articles.views:159] 1
[30/Apr/2014 09:34:33] DEBUG [articles.views:159] 1
[30/Apr/2014 09:34:33] ERROR [django.request:226] Internal Server Error: /articles/edit/updateSlides
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/django/core/handlers/base.py", line 114, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Library/Python/2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/ajay/Tanicode/Tanicode/articles/views.py", line 183, in updateSlides
    a.tags.add(tags)
  File "/Library/Python/2.7/site-packages/taggit/utils.py", line 128, in inner
    return func(self, *args, **kwargs)
  File "/Library/Python/2.7/site-packages/taggit/managers.py", line 134, in add
    if not isinstance(t, self.through.tag_model())
TypeError: unhashable type: 'list'
[30/Apr/2014 09:36:22] DEBUG [articles.views:160] 1
[30/Apr/2014 09:36:22] DEBUG [articles.views:160] 1
[30/Apr/2014 12:39:06] WARNING [django.request:145] Not Found: /articles/favicon.png
[30/Apr/2014 12:39:09] WARNING [django.request:145] Not Found: /favicon.ico
[30/Apr/2014 19:13:48] WARNING [django.request:145] Not Found: /articles/viewArticle/1/favicon.png
[18/May/2014 07:41:04] WARNING [django.request:145] Not Found: /articles/edit/favicon.png
